# Generated by Django 2.1.2 on 2018-10-31 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('russian', '0003_auto_20181026_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_number', models.IntegerField(verbose_name='Word Number')),
                ('time', models.DateTimeField(verbose_name='Time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
