# Generated by Django 2.1.2 on 2018-11-09 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('russian', '0005_user_expression'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_word',
            name='box',
            field=models.IntegerField(default=0, verbose_name='Box'),
        ),
    ]
