# Generated by Django 2.1.2 on 2018-12-01 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('russian', '0007_user_expression_box'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_expression',
            old_name='expression_number',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='user_word',
            old_name='word_number',
            new_name='number',
        ),
    ]
