# Generated by Django 2.1.2 on 2018-11-09 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0006_user_word_box'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_expression',
            name='box',
            field=models.IntegerField(default=0, verbose_name='Box'),
        ),
    ]
