# Generated by Django 2.1.2 on 2018-11-20 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.CharField(max_length=3000, verbose_name='Sentence')),
                ('inyin', models.CharField(max_length=3000, verbose_name='Pinyin')),
                ('equivalence', models.CharField(max_length=3000, verbose_name='Equivalence in English')),
            ],
        ),
        migrations.CreateModel(
            name='User_Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='Time')),
                ('box', models.IntegerField(default=0, verbose_name='Box')),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chinese.Sentence')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
