# Generated by Django 2.1.2 on 2018-11-20 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chinese', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='number',
            field=models.IntegerField(default=0, verbose_name='Number'),
        ),
    ]
