# Generated by Django 2.1.2 on 2018-11-20 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chinese', '0002_sentence_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_sentence',
            name='sentence',
        ),
        migrations.AddField(
            model_name='user_sentence',
            name='sentence_number',
            field=models.IntegerField(default=0, verbose_name='Sentence Number'),
            preserve_default=False,
        ),
    ]
