# Generated by Django 2.1.2 on 2018-11-20 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chinese', '0003_auto_20181120_1717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentence',
            old_name='inyin',
            new_name='pinyin',
        ),
    ]
