# Generated by Django 2.1.2 on 2018-11-23 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chinese', '0004_auto_20181120_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='equivalence',
            field=models.CharField(blank=True, max_length=3000, null=True, verbose_name='Equivalence in English'),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='number',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='pinyin',
            field=models.CharField(blank=True, max_length=3000, null=True, verbose_name='Pinyin'),
        ),
    ]
