# Generated by Django 2.1.2 on 2018-11-30 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chinese', '0005_auto_20181123_1123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_sentence',
            old_name='sentence_number',
            new_name='number',
        ),
    ]
