# Generated by Django 2.1.2 on 2018-12-10 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chinese', '0007_user_timesettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_timesettings',
            name='sentence',
        ),
        migrations.AddField(
            model_name='user_timesettings',
            name='time_settings',
            field=models.CharField(default='[15, 30, 60, 120, 600, 3600, 18000, 86400, 432000, 2160000, 10368000, 31536000]', max_length=3000, verbose_name='Time Settings'),
        ),
    ]
